window.NFL53_DATA = {
  meta: {
    name: "53",
    note: "Demo data. Demo data. Production data should be generated with the 12-start import pipeline in /tools and /sql."
  },
  teams: {
    CAR: { city: "Carolina", name: "Panthers" },
    WAS: { city: "Washington", name: "Washington" },
    NE: { city: "New England", name: "Patriots" },
    BAL: { city: "Baltimore", name: "Ravens" }
  },
  rounds: [
    { team: "CAR", year: 2015 },
    { team: "WAS", year: 2012 },
    { team: "NE", year: 2007 },
    { team: "BAL", year: 2012 }
  ],
  players: {
    "car_cam_newton": { name: "Cam Newton", position: "QB" },
    "car_derek_anderson": { name: "Derek Anderson", position: "QB" },
    "car_jonathan_stewart": { name: "Jonathan Stewart", position: "RB" },
    "car_mike_tolbert": { name: "Mike Tolbert", position: "RB" },
    "car_fozzy_whittaker": { name: "Fozzy Whittaker", position: "RB" },
    "car_ted_ginn": { name: "Ted Ginn Jr.", position: "WR" },
    "car_devin_funchess": { name: "Devin Funchess", position: "WR" },
    "car_philly_brown": { name: "Corey Brown", position: "WR" },
    "car_greg_olsen": { name: "Greg Olsen", position: "TE" },
    "car_ed_dickson": { name: "Ed Dickson", position: "TE" },
    "car_ryan_kalil": { name: "Ryan Kalil", position: "C" },
    "car_michael_oher": { name: "Michael Oher", position: "T" },
    "car_trai_turner": { name: "Trai Turner", position: "G" },
    "car_andrew_norwell": { name: "Andrew Norwell", position: "G" },
    "car_mike_remmers": { name: "Mike Remmers", position: "T" },
    "car_kawann_short": { name: "Kawann Short", position: "DT" },
    "car_star_lotulelei": { name: "Star Lotulelei", position: "DT" },
    "car_charles_johnson": { name: "Charles Johnson", position: "DE" },
    "car_jared_allen": { name: "Jared Allen", position: "DE" },
    "car_luke_kuechly": { name: "Luke Kuechly", position: "LB" },
    "car_thomas_davis": { name: "Thomas Davis", position: "LB" },
    "car_shaq_thompson": { name: "Shaq Thompson", position: "LB" },
    "car_josh_norman": { name: "Josh Norman", position: "CB" },
    "car_bene_benwikere": { name: "Bene Benwikere", position: "CB" },
    "car_kurt_coleman": { name: "Kurt Coleman", position: "S" },
    "car_tre_boston": { name: "Tre Boston", position: "S" },
    "car_graham_gano": { name: "Graham Gano", position: "K" },
    "car_brad_nortman": { name: "Brad Nortman", position: "P" },
    "car_steve_smith": { name: "Steve Smith Sr.", position: "WR" },
    "car_julius_peppers": { name: "Julius Peppers", position: "DE" },
    "car_jake_delhomme": { name: "Jake Delhomme", position: "QB" },
    "car_deangelo_williams": { name: "DeAngelo Williams", position: "RB" },
    "car_muhsin_muhammad": { name: "Muhsin Muhammad", position: "WR" },
    "car_chris_gamble": { name: "Chris Gamble", position: "CB" },
    "car_jordan_gross": { name: "Jordan Gross", position: "T" },

    "was_robert_griffin": { name: "Robert Griffin III", position: "QB" },
    "was_kirk_cousins": { name: "Kirk Cousins", position: "QB" },
    "was_alfred_morris": { name: "Alfred Morris", position: "RB" },
    "was_pierre_garcon": { name: "Pierre Garçon", position: "WR" },
    "was_santana_moss": { name: "Santana Moss", position: "WR" },
    "was_leonard_hankerson": { name: "Leonard Hankerson", position: "WR" },
    "was_chris_cooley": { name: "Chris Cooley", position: "TE" },
    "was_logan_paulsen": { name: "Logan Paulsen", position: "TE" },
    "was_trent_williams": { name: "Trent Williams", position: "T" },
    "was_kory_lichtensteiger": { name: "Kory Lichtensteiger", position: "G" },
    "was_will_montgomery": { name: "Will Montgomery", position: "C" },
    "was_chris_chester": { name: "Chris Chester", position: "G" },
    "was_tyler_polumbus": { name: "Tyler Polumbus", position: "T" },
    "was_barry_cofield": { name: "Barry Cofield", position: "DT" },
    "was_jarvis_jenkins": { name: "Jarvis Jenkins", position: "DE" },
    "was_ryan_kerrigan": { name: "Ryan Kerrigan", position: "LB" },
    "was_london_fletcher": { name: "London Fletcher", position: "LB" },
    "was_rob_jackson": { name: "Rob Jackson", position: "LB" },
    "was_deangelo_hall": { name: "DeAngelo Hall", position: "CB" },
    "was_josh_wilson": { name: "Josh Wilson", position: "CB" },
    "was_madieu_williams": { name: "Madieu Williams", position: "S" },
    "was_reed_doughty": { name: "Reed Doughty", position: "S" },
    "was_kai_forbath": { name: "Kai Forbath", position: "K" },
    "was_sav_rocca": { name: "Sav Rocca", position: "P" },
    "was_chris_samuels": { name: "Chris Samuels", position: "T" },
    "was_clinton_portis": { name: "Clinton Portis", position: "RB" },
    "was_lavar_arrington": { name: "LaVar Arrington", position: "LB" },
    "was_sean_taylor": { name: "Sean Taylor", position: "S" },
    "was_brian_orakpo": { name: "Brian Orakpo", position: "LB" },

    "ne_tom_brady": { name: "Tom Brady", position: "QB" },
    "ne_matt_cassel": { name: "Matt Cassel", position: "QB" },
    "ne_laurence_maroney": { name: "Laurence Maroney", position: "RB" },
    "ne_kevin_faulk": { name: "Kevin Faulk", position: "RB" },
    "ne_randy_moss": { name: "Randy Moss", position: "WR" },
    "ne_wes_welker": { name: "Wes Welker", position: "WR" },
    "ne_donte_stallworth": { name: "Donte' Stallworth", position: "WR" },
    "ne_ben_watson": { name: "Ben Watson", position: "TE" },
    "ne_matt_light": { name: "Matt Light", position: "T" },
    "ne_logan_mankins": { name: "Logan Mankins", position: "G" },
    "ne_dan_koppen": { name: "Dan Koppen", position: "C" },
    "ne_stephen_neal": { name: "Stephen Neal", position: "G" },
    "ne_vince_wilfork": { name: "Vince Wilfork", position: "DT" },
    "ne_richard_seymour": { name: "Richard Seymour", position: "DE" },
    "ne_ty_warren": { name: "Ty Warren", position: "DE" },
    "ne_mike_vrabel": { name: "Mike Vrabel", position: "LB" },
    "ne_tedy_bruschi": { name: "Tedy Bruschi", position: "LB" },
    "ne_osevelt_colvin": { name: "Rosevelt Colvin", position: "LB" },
    "ne_asante_samuel": { name: "Asante Samuel", position: "CB" },
    "ne_ellis_hobbs": { name: "Ellis Hobbs", position: "CB" },
    "ne_rodney_harrison": { name: "Rodney Harrison", position: "S" },
    "ne_james_sanders": { name: "James Sanders", position: "S" },
    "ne_stephen_gostkowski": { name: "Stephen Gostkowski", position: "K" },
    "ne_chris_hanson": { name: "Chris Hanson", position: "P" },
    "ne_julian_edelman": { name: "Julian Edelman", position: "WR" },
    "ne_rob_gronkowski": { name: "Rob Gronkowski", position: "TE" },
    "ne_devin_mccourty": { name: "Devin McCourty", position: "S" },

    "bal_joe_flacco": { name: "Joe Flacco", position: "QB" },
    "bal_tyrod_taylor": { name: "Tyrod Taylor", position: "QB" },
    "bal_ray_rice": { name: "Ray Rice", position: "RB" },
    "bal_vonta_leach": { name: "Vonta Leach", position: "RB" },
    "bal_torrey_smith": { name: "Torrey Smith", position: "WR" },
    "bal_anquan_boldin": { name: "Anquan Boldin", position: "WR" },
    "bal_jacoby_jones": { name: "Jacoby Jones", position: "WR" },
    "bal_ed_dickson": { name: "Ed Dickson", position: "TE" },
    "bal_dennis_pitta": { name: "Dennis Pitta", position: "TE" },
    "bal_michael_oher": { name: "Michael Oher", position: "T" },
    "bal_bryant_mckinnie": { name: "Bryant McKinnie", position: "T" },
    "bal_matt_birk": { name: "Matt Birk", position: "C" },
    "bal_marshal_yanda": { name: "Marshal Yanda", position: "G" },
    "bal_haloti_ngata": { name: "Haloti Ngata", position: "DT" },
    "bal_arthur_jones": { name: "Arthur Jones", position: "DE" },
    "bal_terrell_suggs": { name: "Terrell Suggs", position: "LB" },
    "bal_ray_lewis": { name: "Ray Lewis", position: "LB" },
    "bal_courtney_upshaw": { name: "Courtney Upshaw", position: "LB" },
    "bal_lardarius_webb": { name: "Lardarius Webb", position: "CB" },
    "bal_cary_williams": { name: "Cary Williams", position: "CB" },
    "bal_ed_reed": { name: "Ed Reed", position: "S" },
    "bal_bernard_pollard": { name: "Bernard Pollard", position: "S" },
    "bal_justin_tucker": { name: "Justin Tucker", position: "K" },
    "bal_sam_koch": { name: "Sam Koch", position: "P" },
    "bal_jamal_lewis": { name: "Jamal Lewis", position: "RB" },
    "bal_jonathan_ogden": { name: "Jonathan Ogden", position: "T" },
    "bal_todd_heap": { name: "Todd Heap", position: "TE" },
    "bal_chris_mcalister": { name: "Chris McAlister", position: "CB" }
  },
  rosters: {
    "CAR_2015": ["car_cam_newton", "car_derek_anderson", "car_jonathan_stewart", "car_mike_tolbert", "car_fozzy_whittaker", "car_ted_ginn", "car_devin_funchess", "car_philly_brown", "car_greg_olsen", "car_ed_dickson", "car_ryan_kalil", "car_michael_oher", "car_trai_turner", "car_andrew_norwell", "car_mike_remmers", "car_kawann_short", "car_star_lotulelei", "car_charles_johnson", "car_jared_allen", "car_luke_kuechly", "car_thomas_davis", "car_shaq_thompson", "car_josh_norman", "car_bene_benwikere", "car_kurt_coleman", "car_tre_boston", "car_graham_gano", "car_brad_nortman"],
    "WAS_2012": ["was_robert_griffin", "was_kirk_cousins", "was_alfred_morris", "was_pierre_garcon", "was_santana_moss", "was_leonard_hankerson", "was_chris_cooley", "was_logan_paulsen", "was_trent_williams", "was_kory_lichtensteiger", "was_will_montgomery", "was_chris_chester", "was_tyler_polumbus", "was_barry_cofield", "was_jarvis_jenkins", "was_ryan_kerrigan", "was_london_fletcher", "was_rob_jackson", "was_deangelo_hall", "was_josh_wilson", "was_madieu_williams", "was_reed_doughty", "was_kai_forbath", "was_sav_rocca"],
    "NE_2007": ["ne_tom_brady", "ne_matt_cassel", "ne_laurence_maroney", "ne_kevin_faulk", "ne_randy_moss", "ne_wes_welker", "ne_donte_stallworth", "ne_ben_watson", "ne_matt_light", "ne_logan_mankins", "ne_dan_koppen", "ne_stephen_neal", "ne_vince_wilfork", "ne_richard_seymour", "ne_ty_warren", "ne_mike_vrabel", "ne_tedy_bruschi", "ne_osevelt_colvin", "ne_asante_samuel", "ne_ellis_hobbs", "ne_rodney_harrison", "ne_james_sanders", "ne_stephen_gostkowski", "ne_chris_hanson"],
    "BAL_2012": ["bal_joe_flacco", "bal_tyrod_taylor", "bal_ray_rice", "bal_vonta_leach", "bal_torrey_smith", "bal_anquan_boldin", "bal_jacoby_jones", "bal_ed_dickson", "bal_dennis_pitta", "bal_michael_oher", "bal_bryant_mckinnie", "bal_matt_birk", "bal_marshal_yanda", "bal_haloti_ngata", "bal_arthur_jones", "bal_terrell_suggs", "bal_ray_lewis", "bal_courtney_upshaw", "bal_lardarius_webb", "bal_cary_williams", "bal_ed_reed", "bal_bernard_pollard", "bal_justin_tucker", "bal_sam_koch"]
  },
  franchiseEligible: {
    CAR: ["car_cam_newton", "car_jonathan_stewart", "car_ted_ginn", "car_greg_olsen", "car_ryan_kalil", "car_michael_oher", "car_trai_turner", "car_andrew_norwell", "car_kawann_short", "car_star_lotulelei", "car_charles_johnson", "car_luke_kuechly", "car_thomas_davis", "car_josh_norman", "car_kurt_coleman", "car_graham_gano", "car_steve_smith", "car_julius_peppers", "car_jake_delhomme", "car_deangelo_williams", "car_muhsin_muhammad", "car_chris_gamble", "car_jordan_gross"],
    WAS: ["was_robert_griffin", "was_kirk_cousins", "was_alfred_morris", "was_pierre_garcon", "was_santana_moss", "was_trent_williams", "was_kory_lichtensteiger", "was_will_montgomery", "was_chris_chester", "was_barry_cofield", "was_ryan_kerrigan", "was_london_fletcher", "was_deangelo_hall", "was_josh_wilson", "was_reed_doughty", "was_chris_samuels", "was_clinton_portis", "was_lavar_arrington", "was_sean_taylor", "was_brian_orakpo"],
    NE: ["ne_tom_brady", "ne_randy_moss", "ne_wes_welker", "ne_ben_watson", "ne_matt_light", "ne_logan_mankins", "ne_dan_koppen", "ne_stephen_neal", "ne_vince_wilfork", "ne_richard_seymour", "ne_ty_warren", "ne_mike_vrabel", "ne_tedy_bruschi", "ne_asante_samuel", "ne_ellis_hobbs", "ne_rodney_harrison", "ne_stephen_gostkowski", "ne_julian_edelman", "ne_rob_gronkowski", "ne_devin_mccourty"],
    BAL: ["bal_joe_flacco", "bal_ray_rice", "bal_torrey_smith", "bal_anquan_boldin", "bal_ed_dickson", "bal_dennis_pitta", "bal_michael_oher", "bal_matt_birk", "bal_marshal_yanda", "bal_haloti_ngata", "bal_terrell_suggs", "bal_ray_lewis", "bal_lardarius_webb", "bal_ed_reed", "bal_justin_tucker", "bal_sam_koch", "bal_jamal_lewis", "bal_jonathan_ogden", "bal_todd_heap", "bal_chris_mcalister"]
  }
};
